### ISSUE TITLE
CAHCreator#selectDeck doesn't work on Internet Explorer

### ISSUE THREAD

**Issue by Rylius** [CAHCreator/cah-creator#8]
At least version 11 as that's the only one I have installed. Edge works fine.

No errors on the console, just... doesn't do anything.

**Comment by tjhorner** [comment]
Can't confirm. Here is my IE info:

![image](https://cloud.githubusercontent.com/assets/2646487/21630184/d16fb9e4-d1e3-11e6-8a19-36122121247c.png)

Adding sets from CAH Creator works on CAE:

![image](https://cloud.githubusercontent.com/assets/2646487/21630230/323ec76a-d1e4-11e6-9616-b8f610584580.png)

**Comment by tjhorner** [comment]
Mind giving a little more context? e.g. which page

I assume you're trying to select a deck for Cards Against Equestria, and that works just fine for me on IE 11.

**Comment by Rylius** [comment]
Yeah, tried adding a deck. Using exactly the same IE version.
Also tried switching emulation to IE 10, but that didn't change anything.

I'm *assuming* there's a bug in the code dealing with the same-origin policy... which still doesn't explain why it works on your side.

Chalk it off as "that's just Internet Explorer" and have people use literally any other browser? :)

**Comment by tjhorner** [comment]
Sounds good to me.
